# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository 
        - uses: actions/checkout@v1
          run: |
              echo "A initial message"
        - name: Install-Arduino
          run: |
              export ARDUINO_IDE_VERSION="1.8.13"
              wget --quiet https://downloads.arduino.cc/arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz
              mkdir $HOME/arduino_ide
              tar xf arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz -C $HOME/arduino_ide/
        - name: Install-Tennsyduino
          run: |  
                curl -fsSL https://www.pjrc.com/teensy/td_153/TeensyduinoInstall.linux64 -o TeensyduinoInstall.linux64
                chmod +x TeensyduinoInstall.linux64
                /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
                sleep 3
                export DISPLAY=:1.0
                ./TeensyduinoInstall.linux64 --dir=$HOME/arduino_ide/arduino-1.8.13
                echo "*********************************Another message or command"
        - name: Check-present-working-Directory 
          run: |
                pwd
                ls -r
                cd ..
                ls
        - name: Install-base64
          run: |
                cd $HOME/arduino_ide/arduino-1.8.13/
                ./arduino --install-library "base64"
        - name: Verify-Code 
          run: bash build-sketches.sh

        
        - name: upload-Code 
          uses: actions/upload-artifact@v2
          with:
            name: my-artifact
            path: error.txt
     
